<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Authors>Microlens</Authors>
		<Copyright>Copyright © $([System.DateTime]::Now.Year) Microlens</Copyright>
		<Description></Description>

		<TargetFrameworks>net472;net48;netstandard2.0;net8.0;net10.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>

		<RootNamespace>Microlens.Cache</RootNamespace>
		<AssemblyName>Microlens.Cache</AssemblyName>

		<PackageId>Microlens.Cache</PackageId>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags></PackageTags>
		<EnablePackageValidation>false</EnablePackageValidation>
		<PackageValidationBaselineVersion>1.0.0</PackageValidationBaselineVersion>
		<PackageProjectUrl>https://github.com/microlens-solutions/cache</PackageProjectUrl>

		<RepositoryUrl>https://github.com/microlens-solutions/cache</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
		<PackageReference Include="PolySharp" Version="1.16.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
